# Generated by Django 2.1.2 on 2018-12-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studserviceapp', '0002_auto_20181212_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slika',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
