# Generated by Django 2.1.2 on 2018-12-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studserviceapp', '0003_student_slika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slika',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
    ]
